### ISSUE TITLE
Images in LearnOSM

### ISSUE THREAD

**Issue by severinmenard** [hotosm/learnosm#118]
HI,

I would like to create screenshots for the first version. I have three questions:
1 where to store them?

2 if these broken links are normal within GitHub or not?https://github.com/hotosm/learnosm/blob/e1f4f5b4c650b8b555c5a28a7a0f7707d7969d44/_posts/fr/0200-12-23-editing-with-josm.md

3 how to set the images sizes as currently either too big or too small? http://learnosm.org/fr/beginner/editing-with-josm/

**Comment by pyrog** [comment]
> the best way to do that is to fork the repo, get those images on your computer and manually change the sizes.

:bulb: Some Jekyll plugins could automatically resize images, but I thin you can't see the result with your favorite editor, except if it use plugins…

**Comment by pyrog** [comment]
@severinmenard 
> OK, so basically there is no way to preview the final result before a push.
Wow, one another reason I am not thrilled at all by editing a book on GitHub

I look deeply a [prose.io][1] doc and source code: with an appropriate settings of [prose](), it's easy to upload pictures, drag'n drop them to the page… and preview them :smile: 

@pierzen 
> We could simply hardcode hotosm master repository baseurl.

Did you would say hardcode in the .md like this ?
```markdown
![Screen Copy]({{site.baseurl}}/images/a-screen-copy.png)
```

In practice, you don't (and mustn't) have to do that.

**Comment by Nick-Tallguy** [comment]
If you create an issue an drop an image onto the 'write box' it is added to the image, but is stored as a file eg
``  ![selection_059](https://cloud.githubusercontent.com/assets/6763965/6279872/6f8f8bd4-b89d-11e4-9cd3-61dfa274f680.png)  ``

which could be retrieved later by another editor or just referred to by the person submitting it

**Comment by Nick-Tallguy** [comment]
Like this (this had better work!)
![selection_059](https://cloud.githubusercontent.com/assets/6763965/6279872/6f8f8bd4-b89d-11e4-9cd3-61dfa274f680.png)

**Comment by Nick-Tallguy** [comment]
In comments on this issue in July & August 2013 @severinmenard & @pierzen were trying to work out how to get images into the website. 
One simple solution is to drag & drop them into a an issue. They can then either be captured as a screenshot by someone else updating the site & transferred into or used in the method outlined by me here

https://github.com/Nick-Tallguy/Testing_learnosm/blob/master/images.md

The image is the one created by pierzen & used in his comment on the issue above.

This gives a not very elegant, but working, solution to part of the issue outlined above (the issue has become very wide.

**Comment by althio** [comment]
Thanks for the clarification, I understand your point.

It is certainly a working solution.
The image is then hosted at https://f.cloud.github.com/assets/
It is available and but for keeping our repo tidy it still needs a github
helper to add the file internally to
https://github.com/hotosm/learnosm/tree/gh-pages/images/

At least the non-tech contributor can easily upload the image.

**Comment by pierzen** [comment]
Should we do translations directly into a tracker issue to assure to preview immediately the result? Otherwise, how to use the link to the image, insert it in the markdown document and preview the result?

Or should we have tool elsewhere that gives same functionalities. Once the document would be completed, tech people would take care to transfer to Github.

Working on translation, we need a workflow that let work easily, concentrate on the content, not continually about the technical aspects. As you can see, our comments from august 2013 have not been answered so far. And less people are ready to continue contributing to translation.

In a writer application, you import easily an image, you setup the size and position and see immediatel the result. Prose.io is supposed to provide such functionalities but developpers did not fix the problem of importing images in github.

**Comment by Nick-Tallguy** [comment]
Hi,

I've created this http://nick-tallguy.github.io/en/contribute/translator-images/ at the moment on the staging site but I will add to the main site soon. Accessible from 'contribute' . -  the pencil symbol.

I think this guide plus the use of transifex answers all the questions in this issue.

Closing

**Comment by Nick-Tallguy** [comment]
See also #526
