### ISSUE TITLE
Spelling on Mapping Party

### ISSUE THREAD

**Issue by MarkCupitt** [hotosm/learnosm#310]
Spelling Mistake on main page and sub page???

Additional Fun

Mapping Partay!

**Comment by althio** [comment]
@MarkCupitt I could not find the mentioned mistakes. Could you clarify as much as possible, for instance:
* the page with URL address or github file
* the spelling mistake
* the corrected spelling

**Comment by MarkCupitt** [comment]
Here you go, look under additional fun

https://github.com/hotosm/learnosm/wiki/English-Learning-Guides

Also, follow the link, the google docs are NQR

Cheers

**Comment by althio** [comment]
"Mapping Partay!" sounds like it is intentional slang rather than typo. So is it a spelling mistake to be corrected? I don't know.

Re: google docs
NQR=? outdated? poorly written? not useful?
AFAIK most of this google docs material is 2-year old and was partly moved and updated into the main site.
I am not quite sure what should be kept and removed there.
https://github.com/hotosm/learnosm/wiki/English-Learning-Guides
Not sure about the direct link from the main page too.

Please clarify? @jeffhaack @wonderchook @clairedelune @lxbarth @jueyang @yohanboniface 
Is there an open issue on the subject of updating/migrating google docs?

**Comment by jeffhaack** [comment]
This page was basically a list of all the resources that had been written at the time but not necessarily put into markdown for learnOSM.  I think the idea was to fold it into learnOSM over time.  Definitely the direct link should be removed to this page.  The only reason this wasn't done already was that nobody with 
design prowess was will to step up to reorganize the homepage.

If I'm not mistaken all of the documents in Beginner, Intermediate, and Advanced were reworked and put into the core content of learnOSM last year (you might want to skim over this to make sure there is not any good material in the Google Docs missing from learnOSM).  I don't think the QGIS docs got folded into learnOSM, though I think they could be updated an included if desired.

I'd avoid the slang of "mapping partay" but yes that was definitely intentional.  Still, maybe not understandable to a non-native-speaking audience.

**Comment by Nick-Tallguy** [comment]
Closing. It was either deliberate 'fun' or a mistake. Stale now
