### ISSUE TITLE
Cannot find the chapter for GPS Garmin handhelds

### ISSUE THREAD

**Issue by severinmenard** [hotosm/learnosm#402]
HOT interns in Mongolia are asking the documentation to use GPS Garmin (thttps://github.com/hotosm/learnosm/search?utf8=%E2%9C%93&q=garmin) but I cannot find it anymore on the LearnOSM website

**Comment by Nick-Tallguy** [comment]
Hi @severinmenard 
There is  
English http://learnosm.org/en/beginner/using-gps/  
German http://learnosm.org/de/beginner/using-gps/  
Spanish http://learnosm.org/es/beginner/using-gps/  
French http://learnosm.org/fr/beginner/using-gps/ 
and several other languages for the same section (Swahili / Kiswahili translation is with someone at present).

Hope this helps.

Regards

Nick

**Comment by Nick-Tallguy** [comment]
@severinmenard also this google doc linked off the wiki

https://docs.google.com/document/d/16F7ZGAjryutA5TBPLulhTASFBiXX19ZZ-40EuUcddEw/edit

Nick

**Comment by Nick-Tallguy** [comment]
@severinmenard If you need anything else on this, let me know - I can for instance produce a .pdf &/or an .odt for download of the http://learnosm.org/en/beginner/using-gps/ section if that would help - if it's on the site in a more appropriate language I can produce it in that language.

Regards

Nick

**Comment by Nick-Tallguy** [comment]
message sent via email to @severinmenard in case not getting these messages.

**Comment by Nick-Tallguy** [comment]
Paste of email from @severinmenard - I agree with most, if not all, or his comments & think we ought to consider a reorganize to address those issues.

Thanks for your quick reply!
Actually after a quick search (in Google or my own browser history, I do not remember exactly), I had ended there: http://learnosm.org/en/mobile-mapping/

From such title, I was expecting a direct link to the GPS chapter, but actually you have to guess (or remember) it is within the Beginnerś guide.
IMHO the chapters under the beginner's guide should also be classified in/accessible from the various main topics. GPS should be related to mobile mapping. Or better: make a Field collection main topics (means in the box in bottom left) with smartphones, GPS and FIeld papers. As of now, it is really too much spread out. 
Likewise, everything related to JOSM (from Getting Started with JOSM) under Editing (rather than Detailed editing, what is not very clear - what is the starting point of the detailed editing?)

I'm currently reviewing the sections, in different languages (they appear differently in some of the languages, and will update this issue when I have something more concrete

**Comment by Nick-Tallguy** [comment]
@severinmenard please [view the new staging site](http://nick-tallguy.github.io/en/mobile-mapping/) for the proposed new location for the gps section - have also added 'garmin' in the title.  There are currently lots of broken links within other parts of the staging site - trying out a major change of sections etc..

**Comment by Nick-Tallguy** [comment]
section has now moved to Mapping with Smartphone, GPS or paper, and now has 'garmin' in the title to assist with searching. #431 refers
