### ISSUE TITLE
GPS & Field Papers - move to mobile mapping

### ISSUE THREAD

**Issue by Nick-Tallguy** [hotosm/learnosm#414]
The beginners section of LearnOSM is so long it is difficult to see all of the menus at present. This spreadsheet shows the current position:  https://docs.google.com/spreadsheets/d/1NlJHTYAYpyyF5o9D8UMAsSzFG7lHY2cIi2mzncx530w/edit#gid=1753852254

We have a section **Mobile Mapping** which could easily be adapted to include GPS (Garmin) and Field Papers. 

Propose to move both subjects in all languages to Mobile mapping, updating the text in files that refer to them to show what has been done. 

This is actually a significant update - I will provide a link to a site where you can view this proposed change before we implement it.

**Comment by michael63-osm** [comment]
Definitively pro as far as field papers is concerned.

I hesitate as far as GPS is concerned. The current guide is a detailed instruction how to use a specific Garmin device and in its present form should be moved to the mobile mapping section. Nevertheless, this is learnOSM and not learnHOTOSM. While a GPS is not needed for remote mapping HOT tasks, it is the basis of my mapping after I went hiking.

So we still need some thoughts on sources for editing in a beginners' chapter. For GPS: tell people to select a reasonable sampling interval, make sure they save tracks with timestamps, tell them about GPSBabel and that recording with limited satellite availability, e.g. in gorges, can lead to substantial positioning errors. But there we should not go into details about how to operate specific devices.

I deliberately speak of sources because I miss some points on using some aerial imagery, not using other aerial imagery and not using most printed maps - the ubiquitous copyright issues should be brought to the attention of beginners.

**Comment by gitGOwin** [comment]
@michael63-osm 
Your observation is correct. But I think it can be forgiven if we can overlook how some guides are sometimes HOT-centric, considering how most of the time the authors are associated with HOT. (We were working with HOT and OSM-Indonesia  - with Emir and Adyit when some of these docs were updated some time back.) Perhaps we can consider these guides as a starting point for revised versions of the guides that are more platform neutral.

And that's one of the beauty of collaboratively working with other people.

**Comment by Nick-Tallguy** [comment]
Implemented with #431
