### ISSUE TITLE
German version: Editing a line in Id editor

### ISSUE THREAD

**Issue by fjbehr** [hotosm/learnosm#557]
I think editing the line is possble after using right mouse click, not the left as mentioned in https://learnosm.org/de/beginner/id-editor/
![image](https://user-images.githubusercontent.com/3468961/42684485-81d9f8d2-8690-11e8-9165-2bd529723c2f.png)

I tried to update the file, but was not able to handle the Github and Localization stuuff.

**Comment by michael63-osm** [comment]
Sure you are right. The reason for this problem was that the translation source used for localization did not correspond to the latest English version. I just fixed this now but this problem will exist in nearly all language versions. We have no direct influence when volunteer translators will amend the other translations accordingly.

Thank you for pointing this out!
