### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by lxbarth** [hotosm/learnosm#58]
This issue is to coordinate ongoing French translation.

To contribute:

- Fork `learnosm` to your account
- Translate in `french` branch
- Issue pull request from your `french` branch to the `learnosm/french` branch

Before starting into a translation throw out a quick note here on the thread what you're *immediately* working on.

The immediate part is important, let's not block each other with future plans :-)

**Comment by Nick-Tallguy** [comment]
Fixed some image links in beginner / Introduction. Will fix others as I come to them whilst updating and removing redundant images.

**Comment by Nick-Tallguy** [comment]
Closing this as we have a 'working' system using Transifex at the moment. This isn't fixed in stone though, and I'd welcome any suggestions as to how to improve or simplify. There are currently variations in the menus depending on the language you are viewing - no intention to alter this unless there is discussion first.

**Comment by yohanboniface** [comment]
http://gitbook.com/ may be an option to consider.

**Comment by Nick-Tallguy** [comment]
Yes, that looks interesting. Needs further investigation. We currently average 500 people a day visiting LearnOSM, many using only languages other than English, so we'd have to make sure that the language options are covered ok. Also the search engines know where we are now.

I'll try to spend some time investigating.
