### ISSUE TITLE
Outdated translations

### ISSUE THREAD

**Issue by jmacura** [hotosm/learnosm#613]
Hi!

If I go to [learnosm.org](learnosm.org) and switch language to cs (https://learnosm.org/cs/), then I can see version of translation which is more than 9 months old. Can I help somehow with updating obsolete translation strings on the website? It is updated on Transifex.

Thanks!

**Comment by michael63-osm** [comment]
Hi,

I just saw that you updated several translations on Transifex. These translations are never immediately visible on the website. The whole process is outlined in https://learnosm.org/en/contribute/translator/ 
In short: at an early European morning a script pulls all new translations from the past 24 hours onto a staging site where they should then be visible. Pulling things from the staging site to the production site so that they will be visible on learnosm.org is a manual process because we would like to have some quality control. Sometimes formatting errors which may break parts of the website are accidentally introduced as well as broken links. There is no fixed schedule for this last step, it also depends on the level of translation activity. And finally on our own availability  - we are all volunteers who maintain that in our spare time.

Please be a little bit patient, translations definitively will not be lost but are always welcome

Best Regards

Michael

**Comment by jmacura** [comment]
This is a misunderstood, @michael63-osm .
I am not talking about the several changes I have made this morning. I am talking about changes which have been done on Transifex several months ago, but are still not visible on the production site. Compare e.g. this string: 
![image](https://user-images.githubusercontent.com/5598693/81085091-0b8bd080-8ef7-11ea-9a59-d9bdf5d79e9c.png)
with this history:
![image](https://user-images.githubusercontent.com/5598693/81085136-1a728300-8ef7-11ea-9396-a2a15eba4252.png)
which is not yet on the website:
![image](https://user-images.githubusercontent.com/5598693/81085203-30804380-8ef7-11ea-83ff-9c881eb57604.png)

I do not expect magic to happen immediately 😉

**Comment by michael63-osm** [comment]
Ok, this is a string from the essential_setup resource. And I understand how this might have gone unnoticed. This resource is not one page which gets downloaded, installed and is visible as one page. This is a collection of strings which are entered at various places in the configuration files of the website. I guess that initially not all strings were translated and once the remaining ones were added we simply missed that.  I'll take care of that later today, thank you for notifying us about that.

**Comment by jmacura** [comment]
Thanks for explanation, it makes sense now. And thanks for taking care about it!

What is the correct process then, when someone updates translations of the main page? Shall it be notified somewhere (here)?

**Comment by jmacura** [comment]
Thanks again for the update, @michael63-osm . Could you also update the strings https://www.transifex.com/hotosm/learnosm-1/translate/#cs/1-essential_setuptxt/51694822 ,
https://www.transifex.com/hotosm/learnosm-1/translate/#cs/1-essential_setuptxt/51694826 and
https://www.transifex.com/hotosm/learnosm-1/translate/#cs/1-essential_setuptxt/52755544 ?
Thanks!

**Comment by michael63-osm** [comment]
done on both the staging and production sites
