### ISSUE TITLE
Add StreetComplete page

### ISSUE THREAD

**Issue by FloEdelmann** [hotosm/learnosm#633]
In the ["Mapping with a Smartphone, GPS or Paper" chapter](https://learnosm.org/en/mobile-mapping/), a page about mapping with [StreetComplete](https://github.com/westnordost/StreetComplete) should be added.

I know it's "just" completing quests about existing map features and not "real" manual mapping, but it's an easy and fun way to contribute to OSM with a smartphone.

**Comment by michael63-osm** [comment]
Thank you for pointing us at this. We know that the chapter on mobile mapping is pretty much out of date and refreshing this is on our todo list. But as we are just a few volunteers this might take a while.

**Comment by rouelibre1** [comment]
I'd would love to see this section updated, and help translate it in French

**Comment by matkoniecz** [comment]
@michael63-osm So adding StreetComplete page would be welcome? I would be happy to add it but I have a conflict of interest here (I am one of people making it).

**Comment by michael63-osm** [comment]
We have no problem with that as long as it fits with the style of other pages, i.e. presents the features in a rather technical way. We do not want to add simple marketing flyers containing sentences like 'this is world's best software to accomplish anything you might ever dream of" - I think you get the point.

We already received the occasional input particularly for the mobile mapping chapter and after a quick review we added it. There was one app which we did not cover because it advertised itself as a simple GPS track visualizer but required all kinds of permissions from reading your list of contacts to sending SMS. Typically when covering software I would like to install it myself to have a look at it but in that case I stopped when being asked to grant all permissions imaginable.

If a project offers good documentation on its homepage then a page on LearnOSM might simply contain a general description what it is about and where it differs from other products and then provide a link to the documentation. E.g. when I revised the documentation about QGIS I mentioned that there are tons of tutorials and books out there and that there is no way we can adequately cover the complete product. But on our website people will be particularly interested in how to load OSM data and how to handle them. So that is what I covered in our small guide.

If you want to add something in Markdown try to keep formatting aligned with the other guides. Usually our pages do not contain fancy formatting so if you feel more comfortable writing plain text or some open document format this will not be a big problem. For Markdown you may want to have a look at our translators' guide (https://learnosm.org/en/contribute/translator/#translating-a-module---using-0200-12-31-beginner-as-an-example) which informs translators what are special commands for site navigation.

Just ask if anything is unclear - general questions may best go to learnosm@hotosm.org and keep in mind that we are all volunteers who take care in our spare time. Please be patient if an answer takes a while.

**Comment by michael63-osm** [comment]
Some things take way longer than we would like but in the meantime a contributor found the time and had the expertise to write an in-depth guide  on StreetComplete: https://learnosm.org/en/mobile-mapping/streetcomplete/

LearnOSM now covers MapSwipe as well and a revised version of the guide on Vespucci is nearly finished.
