### ISSUE TITLE
Sudden unexplained Spanish(?)

### ISSUE THREAD

**Issue by matkoniecz** [hotosm/learnosm#649]
https://learnosm.org/en/josm/opendata-plugin/

![screen06](https://user-images.githubusercontent.com/899988/147072615-dc83d81a-656d-4abd-aacb-aa146cb965ab.png)

**Comment by michael63-osm** [comment]
Thanks for pointing this out. I'll have to reject the associated pull request because the root cause is in Transifex which we use for translations. If I do not fix it there then the github contents would get overridden with the next update of translated files.
Updates to our staging site happen every morning and I'll find time to integrate this some time tomorrow.
